name: Render on VPS

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Manually trigger karne ke liye

jobs:
  render:
    runs-on: self-hosted  # VPS ke runner pe chalega
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y ffmpeg blender  # Rendering ke liye packages install karega

      - name: Run Blender Render Task
        run: |
          blender -b scene.blend -o //output -F PNG -x 1 -a  # Scene render karega

      - name: Upload Rendered Output
        uses: actions/upload-artifact@v4
        with:
          name: render-output
          path: output/
